# HDMA-Data
- addr: 0x808639
  type: Data
  db: 0x8E

- addr: 0x808659
  type: Data
  db: 0x80

- addr: 0x80866D
  type: Data
  db: 0x8E


# Overrides immediate opcodes in bank 80 to be pointers
- addr: 0x809B56
  type: Data
  db: 0x80

- addr: 0x809B5E
  type: Data
  db: 0x80

- addr: 0x808980
  type: Pointer
  db: 0x80

- addr: [0x80AE76, 0x80AE7D]
  type: Pointer
  db: 0x80

- addr: [0x80AE08, 0x80AE0F]
  type: Pointer
  db: 0x80

# Elevator bits
- addr: [0x80CD46, 0x80CD51]
  type: Pointer
  db: 0x80

# Savestation data
- addr: [0x80C4B5, 0x80C4C4]
  type: Pointer
  db: 0x80

- addr: [0x80C4C5, 0x80CD06]
  type: Struct
  struct: SaveStationData

# Sets the reset vectors to pointers
- addr: [0x80FFE0, 0x80FFFF]
  type: Pointer
