# Struct definitions that can be used in overrides to tag data as this struct
#

- name: SaveStationData
  fields:
    - { name: RoomPtr, offset: 0, length: 2, type: Pointer, db: 0x8F }
    - { name: DoorPtr, offset: 2, length: 2, type: Pointer, db: 0x83 }
    - { name: DoorBTS, offset: 4, length: 2, type: Data }
    - { name: ScreenX, offset: 6, length: 2, type: Data }
    - { name: ScreenY, offset: 8, length: 2, type: Data }
    - { name: SamusY, offset: 10, length: 2, type: Data }
    - { name: SamusX, offset: 12, length: 2, type: Data }